---
- hosts: all
  connection: local
  gather_facts: False
  vars:
    app_name: Firefox
    app_name_pretty: Firefox
    app_url: "https://download.mozilla.org/?product=firefox-31.0-SSL&os=osx&lang=en-US"
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/Firefox/
    downloads: ~/.ansible-downloads/
    creates: /Applications/Firefox.app

  tasks:
   - include: ../install/{{install_method}}.yml
