---
- hosts: all
  connection: local
  gather_facts: False
  sudo: True

  vars:
    app_name: Vagrant
    app_name_pretty: Vagrant
    app_url: "https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.3.dmg"
    installer_type: pkg
    install_method: dmg
    install_target: /Volumes/Macintosh\ HD
    mount_path: /Volumes/Vagrant/
    downloads: ~/.ansible-downloads/
    creates: /Applications/Vagrant/bin/vagrant

  tasks:
    - include: ../install/{{install_method}}.yml
